apiVersion: v1
kind: Service
metadata:
  name: covid-aggregate
  labels:
    app: covid-aggregate
    component: covid-aggregate
    type: covid-demo
    spring-deployment-id: covid-aggregate
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: covid-aggregate-port
      targetPort: 8080
      protocol: TCP
  selector:
    app: covid-aggregate
    component: covid-aggregate